nopackage: Add comment (#5)
* nopackage: Try adding a comment

* nopackage: correct comment workflow

* nopackage: continue on error

* nopackage: log PR number

* nopackage: try a different comment action

* nopackage: empty

* nopackage: Always run comment action

* nopackage: explicity specify GITHUB_TOKEn

* nopackage: explicit revision for actions-commit-pull-request

* nopackage: now try explicit version without explicit token

* nopackage: back to v2 and only on failure

* nopackage: Show the contents of faulty_commits.txt

* nopackage: fail action if necessary

* nopackage: Reformat message for comment, don't raise in python script

* nopackage: write all faulty commits to output file

* nopackage: Play with formatting

* nopackage: bugfix

* nopackage: Add reactions to the comment for more obnoxiousness

* nopackage: reformat comment message

* nopackage: further comment formatting

* nopackage: further formatting

* nopackage: try to run some jobs only on fail

* nopackage: Also set output on success, show output

* nopackage: proper cat

* nopackage: extra logging

* nopackage: compare output files

* nopackage: show step output

* nopackage: hopefully better condition

* nopackage: perhaps we need to check for string

* nopackage: filePath must exist

* nopackage: maybe the if needs to be first

* nopackage: set output in job step instead of python

* nopackage: Set faulty-commits to correct value

* nopackage: try with needs

* nopackage: needs is a list

* nopackage: different needs data

* nopackage: try quotes

* nopackage: try present/absent instead of true/false

* nopackage: always comment, and check PR title as well

* nopackage: extra newline

* nopackage: empty commit

* nopackage: Another syntax to try

diff --git a/.github/workflows/validate-commit-message.yaml b/.github/workflows/validate-commit-message.yaml
--- a/.github/workflows/validate-commit-message.yaml
+++ b/.github/workflows/validate-commit-message.yaml
@@ -15,8 +15,28 @@ jobs:
           python-version: '3.10'
 
       - name: Validate commit messages
+        id: commit-message-validator
+        continue-on-error: true
         run: |
           echo "Deepening shallow clone to ${{ github.event.pull_request.commits }} commits"
+          echo "PR number is ${{ github.event.pull_request.number }}"
           git fetch --deepen=$((${{ github.event.pull_request.commits }} - 1))
           pip install gitpython
-          python ./.github/workflows/validate-commit-message.py
+          python ./.github/workflows/validate-commit-message.py --title "${{ github.event.pull_request.title }}" || true
+
+      - name: Show output
+        run: |
+          echo "Output: ${{ steps.commit-message-validator.outputs.faulty-commits }}"
+
+      - name: Add comment to PR
+        if: ${{ steps.commit-message-validator.outputs.faulty-commits == 'true' }}
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          filePath: faulty_commits.txt
+          reactions: eyes, confused, rocket
+
+      - name: Fail the action
+        if: ${{ steps.commit-message-validator.outputs.faulty-commits == 'true' }}
+        run: |
+          echo "Faulty commit messages found - failing"
+          exit 1
